---
- name: Install Apache server
  hosts: all
  become: yes
  tasks:
    - name: Install Apache server
      apt:
        name: apache2
        state: present

    - name: Print success message
      debug:
        msg: "Apache successfully installed"

    - name: Check Apache service status
      service_facts:
        
    - name: Check the Apache status
      debug:
        msg: >
          Apache is {{
            'running' if services['apache2'].state == 'running'
            else 'not running'
          }}

  
