---
- name: Create a sample file with content on the remote server
  hosts: all
  become: yes
  tasks:
    - name: Create a sample file at /tmp/sample.txt
      copy:
        content: "This file was created by Ansible Tower"
        dest: /tmp/sample.txt

