---
- name: Prasanna
  hosts: all
  tasks: 
    - name: check date
      shell: date
      register: out
    - name: check uptime
      shell: uptime
    - name: Check currently logged in users
      shell: who
    - name: Check disk usage
      shell: df -h
    - name: Check memory usage
      shell: free -h
    - name: Show running services
      debug:
      var: running_services.stdout

