---
- name: Prasanna
  hosts: all
  tasks: 
    - name: check date
      shell: date
      register: out
    - name: check uptime
      shell: uptime
    - name: Check currently logged in users
      shell: who

